dependency:
  name: galaxy
  options:
    requirements-file: ../requirements.yml
ansible:
  executor:
    args:
      ansible_playbook:
        - --inventory=${MOLECULE_SCENARIO_DIRECTORY}/hosts
scenario:
  test_sequence:
    - create
    - prepare
    - converge
    - destroy
